defmodule Mix.Tasks.Claw.Setup do
  @shortdoc "Interactive setup wizard for Clawixir — configure LLM + channels"
  @moduledoc """
  Interactive setup wizard for Clawixir.

  Guides you through configuring:
  1. LLM provider (Anthropic / OpenAI) + API key
  2. Telegram channel (bot token + auto-webhook)
  3. WhatsApp channel (access token + phone number ID)
  4. WebChat (always-on, no config needed)

  Writes validated settings to `.env`.

  ## Usage

      mix claw.setup

  """
  use Mix.Task

  @env_file ".env"

  @impl Mix.Task
  def run(_args) do
    # Start Req for HTTP calls (token validation, webhook registration)
    Mix.Task.run("app.config")
    Application.ensure_all_started(:req)

    header()
    config = %{}

    config = step_llm(config)
    config = step_telegram(config)
    config = step_whatsapp(config)
    config = step_phoenix(config)

    write_env(config)
    summary(config)
  end

  # ── Header ──────────────────────────────────────────────────────────────

  defp header do
    IO.puts("")
    IO.puts(IO.ANSI.cyan() <> "  🦞  Clawixir Setup Wizard" <> IO.ANSI.reset())
    IO.puts(IO.ANSI.faint() <> "  ─────────────────────────────────────" <> IO.ANSI.reset())
    IO.puts("")
    IO.puts("  This wizard will configure your .env file.")
    IO.puts("  Press Enter to skip any optional step.")
    IO.puts("")
  end

  # ── Step 1: LLM Provider ───────────────────────────────────────────────

  defp step_llm(config) do
    section("1", "LLM Provider")

    provider = choose("  Provider", ["anthropic", "openai"], "anthropic")

    api_key = secret("  #{provider_label(provider)} API Key")

    model = case provider do
      "anthropic" -> ask("  Model", "claude-sonnet-4-20250514")
      "openai"    -> ask("  Model", "gpt-4o")
    end

    config
    |> Map.put(:llm_provider, provider)
    |> Map.put(:llm_model, model)
    |> Map.put(:api_key, api_key)
    |> Map.put(:api_key_name, api_key_env(provider))
  end

  # ── Step 2: Telegram ────────────────────────────────────────────────────

  defp step_telegram(config) do
    section("2", "Telegram Channel")

    token = ask("  Bot Token (from @BotFather, or Enter to skip)", "")

    if token == "" do
      IO.puts(IO.ANSI.faint() <> "  ⏭  Telegram skipped" <> IO.ANSI.reset())
      config
    else
      # Validate the token
      case validate_telegram_token(token) do
        {:ok, bot_name} ->
          ok("Connected as @#{bot_name}")

          # Offer auto-webhook registration
          webhook_url = ask("  Webhook URL (e.g. https://your-domain.com, or Enter to skip)", "")

          if webhook_url != "" do
            full_url = String.trim_trailing(webhook_url, "/") <> "/api/webhooks/telegram"
            case register_telegram_webhook(token, full_url) do
              :ok -> ok("Webhook registered → #{full_url}")
              {:error, reason} -> warn("Webhook registration failed: #{inspect(reason)}")
            end
          end

          Map.put(config, :telegram_bot_token, token)

        {:error, reason} ->
          warn("Token validation failed: #{inspect(reason)}")
          retry = ask("  Save anyway? (y/n)", "y")
          if retry == "y", do: Map.put(config, :telegram_bot_token, token), else: config
      end
    end
  end

  # ── Step 3: WhatsApp ────────────────────────────────────────────────────

  defp step_whatsapp(config) do
    section("3", "WhatsApp Channel")

    access_token = ask("  Access Token (Meta Cloud API, or Enter to skip)", "")

    if access_token == "" do
      IO.puts(IO.ANSI.faint() <> "  ⏭  WhatsApp skipped" <> IO.ANSI.reset())
      config
    else
      phone_id = ask("  Phone Number ID", "")
      verify_token = ask("  Webhook Verify Token", generate_verify_token())

      config
      |> Map.put(:whatsapp_access_token, access_token)
      |> Map.put(:whatsapp_phone_number_id, phone_id)
      |> Map.put(:whatsapp_verify_token, verify_token)
    end
  end

  # ── Step 4: Phoenix ─────────────────────────────────────────────────────

  defp step_phoenix(config) do
    section("4", "Phoenix Settings")

    secret = generate_secret()
    IO.puts(IO.ANSI.faint() <> "  Auto-generated SECRET_KEY_BASE" <> IO.ANSI.reset())

    port = ask("  Port", "4000")

    config
    |> Map.put(:secret_key_base, secret)
    |> Map.put(:port, port)
  end

  # ── Write .env ──────────────────────────────────────────────────────────

  defp write_env(config) do
    content = """
    # Clawixir — generated by mix claw.setup
    # #{DateTime.utc_now() |> DateTime.to_iso8601()}

    # ─── LLM Provider ─────────────────────────────────────────────────────────────
    LLM_PROVIDER=#{config[:llm_provider]}
    LLM_MODEL=#{config[:llm_model]}
    #{config[:api_key_name]}=#{config[:api_key]}

    # ─── Channels ──────────────────────────────────────────────────────────────────
    TELEGRAM_BOT_TOKEN=#{config[:telegram_bot_token] || ""}
    WHATSAPP_ACCESS_TOKEN=#{config[:whatsapp_access_token] || ""}
    WHATSAPP_PHONE_NUMBER_ID=#{config[:whatsapp_phone_number_id] || ""}
    WHATSAPP_VERIFY_TOKEN=#{config[:whatsapp_verify_token] || ""}

    # ─── Phoenix ──────────────────────────────────────────────────────────────────
    SECRET_KEY_BASE=#{config[:secret_key_base]}
    PORT=#{config[:port]}

    # ─── External Services ─────────────────────────────────────────────────────────
    BROWSER_SERVICE_URL=http://localhost:4001
    AI_SERVICE_URL=http://localhost:5001

    # ─── BEAM Clustering (optional) ────────────────────────────────────────────────
    CLUSTER_ENABLED=false
    CLUSTER_STRATEGY=gossip
    """

    File.write!(@env_file, content)
  end

  # ── Summary ─────────────────────────────────────────────────────────────

  defp summary(config) do
    IO.puts("")
    IO.puts(IO.ANSI.green() <> "  ✅ Setup complete! .env written." <> IO.ANSI.reset())
    IO.puts("")
    IO.puts("  " <> IO.ANSI.bright() <> "Configured:" <> IO.ANSI.reset())
    IO.puts("  • LLM: #{config[:llm_provider]} (#{config[:llm_model]})")
    if config[:telegram_bot_token], do: IO.puts("  • Telegram: ✅ enabled")
    if config[:whatsapp_access_token], do: IO.puts("  • WhatsApp: ✅ enabled")
    IO.puts("  • WebChat:  ✅ always-on at /chat")
    IO.puts("")
    IO.puts("  " <> IO.ANSI.bright() <> "Next steps:" <> IO.ANSI.reset())
    IO.puts("  1. mix deps.get")
    IO.puts("  2. mix ecto.setup")
    IO.puts("  3. mix phx.server")
    IO.puts("  4. Open http://localhost:#{config[:port]}/chat")
    IO.puts("")
  end

  # ── Telegram API helpers ────────────────────────────────────────────────

  defp validate_telegram_token(token) do
    case Req.get("https://api.telegram.org/bot#{token}/getMe") do
      {:ok, %{status: 200, body: %{"result" => %{"username" => name}}}} -> {:ok, name}
      {:ok, %{status: 401}} -> {:error, :invalid_token}
      {:ok, %{status: status}} -> {:error, {:http, status}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp register_telegram_webhook(token, url) do
    case Req.post("https://api.telegram.org/bot#{token}/setWebhook", json: %{url: url}) do
      {:ok, %{status: 200, body: %{"ok" => true}}} -> :ok
      {:ok, %{body: body}} -> {:error, body}
      {:error, reason} -> {:error, reason}
    end
  end

  # ── Interactive helpers ─────────────────────────────────────────────────

  defp section(num, title) do
    IO.puts("")
    IO.puts(IO.ANSI.cyan() <> "  [#{num}] #{title}" <> IO.ANSI.reset())
    IO.puts(IO.ANSI.faint() <> "  ───────────────────────────" <> IO.ANSI.reset())
  end

  defp ask(prompt, default) do
    suffix = if default != "", do: IO.ANSI.faint() <> " [#{default}]" <> IO.ANSI.reset(), else: ""
    input = IO.gets("#{prompt}#{suffix}: ") |> String.trim()
    if input == "", do: default, else: input
  end

  defp secret(prompt) do
    # For API keys — we can't truly hide input in Mix tasks, but we label it clearly
    ask(prompt, "")
  end

  defp choose(prompt, options, default) do
    opts_str = Enum.join(options, "/")
    ask("#{prompt} (#{opts_str})", default)
  end

  defp ok(msg) do
    IO.puts(IO.ANSI.green() <> "  ✅ #{msg}" <> IO.ANSI.reset())
  end

  defp warn(msg) do
    IO.puts(IO.ANSI.yellow() <> "  ⚠️  #{msg}" <> IO.ANSI.reset())
  end

  defp provider_label("anthropic"), do: "Anthropic"
  defp provider_label("openai"), do: "OpenAI"
  defp provider_label(other), do: other

  defp api_key_env("anthropic"), do: "ANTHROPIC_API_KEY"
  defp api_key_env("openai"), do: "OPENAI_API_KEY"
  defp api_key_env(_), do: "API_KEY"

  defp generate_secret do
    :crypto.strong_rand_bytes(48) |> Base.encode64(padding: false)
  end

  defp generate_verify_token do
    :crypto.strong_rand_bytes(16) |> Base.encode16(case: :lower)
  end
end
